name: Production Deployment
on:
  push:
    branches: [main]
jobs:

  run_tests:
   name: "Testing"
   runs-on: ubuntu-latest
   env:
    working-directory: .
   defaults:
    run:
     working-directory: ${{ env.working-directory }}

   steps:
  # Чекаутим код
   - uses: actions/checkout@master
   # Устанавливаем python нужной версии
   - uses: actions/setup-python@v1
     with:
       python-version: '3.10.15'
       architecture: 'x64'
   - name: Install requirements
   # Устанавливаем зависимости
     run: pip install -r requirements.txt
   - name: black
     run: black --diff --check .
   - name: mypy
     run: mypy .
   - name: isort
     run: isort --check-only .
   - name: flask8
     run: flake8 .
   - name: Run main
     run: python -m main 
   - name: Run tests
     run: pytest test_flask.py
